# This is a basic workflow to help you get started with Actions

name: CI
on:
   push:
    branches: [main]
   pull-request:
    branches:["main"]


jobs:
    build:
        runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        
    -name : Run a multi-line script
    run: |
        echo Getting variable from Application ${{ vars.APPLICATIONNAME }} and Environment is ${{ vars.ENVIRONMENT }}
        ls -ltr
        echo tes, and deploy your project.
